Issue-3-add-guests-to-list | Natalie Nunez
NatalieNunez/final-project pull request #8
Opened 2021-05-29 21:29 UTC by NatalieNunez

![issue-3](https://user-images.githubusercontent.com/74742148/120085110-40327300-c08a-11eb-89e2-6e50011b9323.gif)

2021-05-29 21:37 UTC, thebearingedge requested changes
Great, just some minor changes.

2021-05-29 21:37 UTC, thebearingedge commented on client/guest/guest-form.jsx
> +    const form = document.getElementById('guest-form');
we don't query the DOM like this in React. is `event.target` what you're looking for?

2021-05-29 21:37 UTC, thebearingedge commented on client/guest/guest-form.jsx
> +    form.reset();
If you are using state to track values, it's better to use `setState` to reset them.

2021-05-29 21:37 UTC, thebearingedge commented on client/guest/guest-form.jsx
> +      isClicked: false,
`isClicked` isn't as clear as `modalOpen`.

2021-05-29 21:37 UTC, thebearingedge commented on client/guest/guest-form.jsx
> +  }
Is this necessary here? i saw it in another file and wasn't too sure

2021-05-29 22:48 UTC, NatalieNunez commented
Request changes fixed
removed dom query, reset form using setState, updated state names for clarity, removed repeated code

2021-05-30 00:19 UTC, thebearingedge approved these changes

2021-05-30 02:04 UTC, merged